name: Run Terraform
description: Plan and apply required infrastructure

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS secret Access Key'
    required: true

runs:
  using: composite
  steps:
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2

    - name: Terraform Init
      run: cd terraform && terraform init && terraform validate -no-color && terraform plan && terraform apply --auto-approve
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
