name: Deploy Vercel
description: Deploy Vercel in two modes

inputs:
  vercel-token:
    type: string
    description: 'Vercel token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Vercel CLI
      run: npm install --global vercel@canary

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ inputs.vercel-token }}

    - name: Build Project Artifacts
      run: vercel build --token=${{ inputs.vercel-token }}

    - name: PREVIEW Vercel Deployment
      run: |
        DEPLOY_OUTPUT="$(vercel deploy --token=${{ inputs.vercel-token }})"
        DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep http | tail -n 1)
        echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
      shell: bash

    - name: Comment with preview URL
      uses: actions/github-script@v7
      with:
        script: |
          const { DEPLOY_URL } = process.env;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🔍 Preview URL: ${DEPLOY_URL}`
          })
