name: Lint and unit tests
description: Run linting code and run unit tests

runs:
  using: 'composite'
  steps:
    - name: Lint code
      run: npm run lint
      shell: bash

    - name: Unit tests
      run: npm run test
      shell: bash
