name: Deploy - Netlify

on:
  workflow_call:
    # secrets:
    #   NETLIFY_AUTH_TOKEN:
    #     required: true
    #   NETLIFY_SITE_ID:
    #     required: true

jobs:
  deploy-netlify:
    runs-on: windows-latest
    environment:
      name: 'Development'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Lint code and run unit tests
        uses: ./.github/actions/lint

      - name: Build app
        run: npm run build
        env:
          VITE_ENVIRONMENT: ${{ github.ref_name == 'master' && 'DEV' }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          github-deployment-environment: 'Development'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

        timeout-minutes: 1
