name: Deploy - AWS

on:
  workflow_call:

jobs:
  deploy-aws:
    runs-on: windows-latest
    environment:
      name: 'Production'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Lint code and run unit tests
        uses: ./.github/actions/lint

      - name: Build app
        run: npm run build
        env:
          VITE_ENVIRONMENT: 'PROD'
          VITE_S3_IMAGES_BUCKET: ${{ secrets.VITE_S3_IMAGES_BUCKET }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Terraform Apply
        uses: ./.github/actions/terraform-apply
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Deploy to AWS
        run: aws s3 sync dist s3://rm-cicd

      - name: Deploy images to AWS s3
        run: aws s3 sync dist/resources/img s3://rm-cicd-images --exclude "*" --include "*.jpg" --include "*.png"

      - name: Clear Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID}} --paths "/*"
