name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy-netlify:
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit
    # secrets:
    #   NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    #   NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  deploy-vercel:
    needs: deploy-netlify
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit

  deploy-aws:
    needs: deploy-vercel
    uses: ./.github/workflows/deploy-aws.yml
    secrets: inherit
