name: E2E - tests

on:
  workflow_dispatch:
  schedule:
    - cron: '* */2 * * *'

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    environment: 'Development'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: './.github/actions/setup-project'

      - name: Lint code and run unit tests
        uses: './.github/actions/lint'

      - name: Run e2e tests
        uses: './.github/actions/e2e-tests'
        with:
          baseUrl: ${{ vars.STAGE_URL }}
          mode: 'preview'

      - name: Send notification
        if: ${{ success() }}
        uses: './.github/actions/notify-webhook'
        with:
          message: 'Job success!'
          webhook_url: ${{ secrets.NOTIFY_WEBHOOK_URL }}

      - name: Send notification
        if: ${{ failure() }}
        uses: './.github/actions/notify-webhook'
        with:
          message: 'Job failed!'
          webhook_url: ${{ secrets.NOTIFY_WEBHOOK_URL }}
